@echo off
chcp 65001 >nul
set "LAMP_DIR=%~dp0小灯当家"
for %%F in ("小灯当家.exe" "icudtl.dat" "resources\app.asar" "chrome_100_percent.pak" "chrome_200_percent.pak" "v8_context_snapshot.bin" "ffmpeg.dll" "resources.pak") do (
 if not exist "%LAMP_DIR%\%%~F" (
  echo 缺少运行文件：%%~F
  echo 请重新完整解压整个压缩包。不要单独移动 exe 或这个启动文件。
  pause
  exit /b 1
 )
)
powershell.exe -NoProfile -NonInteractive -EncodedCommand JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQA9ACcAUwB0AG8AcAAnADsAIAAkAGQAaQByAD0AJABlAG4AdgA6AEwAQQBNAFAAXwBEAEkAUgA7ACAAJABkAGUAcwBrAHQAbwBwAD0AWwBFAG4AdgBpAHIAbwBuAG0AZQBuAHQAXQA6ADoARwBlAHQARgBvAGwAZABlAHIAUABhAHQAaAAoACcARABlAHMAawB0AG8AcAAnACkAOwAgACQAdwA9AE4AZQB3AC0ATwBiAGoAZQBjAHQAIAAtAEMAbwBtAE8AYgBqAGUAYwB0ACAAVwBTAGMAcgBpAHAAdAAuAFMAaABlAGwAbAA7ACAAJABzAD0AJAB3AC4AQwByAGUAYQB0AGUAUwBoAG8AcgB0AGMAdQB0ACgAKABKAG8AaQBuAC0AUABhAHQAaAAgACQAZABlAHMAawB0AG8AcAAgACcAD1xvcFNftlsuAGwAbgBrACcAKQApADsAIAAkAHMALgBUAGEAcgBnAGUAdABQAGEAdABoAD0ASgBvAGkAbgAtAFAAYQB0AGgAIAAkAGQAaQByACAAJwAPXG9wU1+2Wy4AZQB4AGUAJwA7ACAAJABzAC4AVwBvAHIAawBpAG4AZwBEAGkAcgBlAGMAdABvAHIAeQA9ACQAZABpAHIAOwAgACQAcwAuAEQAZQBzAGMAcgBpAHAAdABpAG8AbgA9ACcAD1xvcFNftlsnADsAIAAkAHMALgBTAGEAdgBlACgAKQA7ACAAVwByAGkAdABlAC0ASABvAHMAdAAgACcATGhil+tfd2O5ZQ9f8l0bUvpeAjD3i91PWXWfU4dl9k45WQIwJwA=
if errorlevel 1 echo 创建失败，请检查桌面是否可写。
pause
